Algoritmo "FazSomaProcedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/02/2022
Var
   x,y:inteiro
Procedimento soma ( a,b:inteiro  )
inicio
   Escreval("recebi o valor ",a)
   Escreval("recebi o valor ",b)
   Escreval("a soma dos valores é ",a+b)
FimProcedimento
Inicio

   x <-5
   y <-3
   soma (x,y)

FimAlgoritmo