Algoritmo "Valores-pares-para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2022
Var

   cont,valor:inteiro



Inicio
 escreva("digite um valor")
 leia (valor)
 se(valor %2=1)então
 valor<- valor
 fimse
 para cont<- valor ate 0 passo -2 faca
 escreval (cont)
 fimpara
Fimalgoritmo